#!/usr/bin/env python3
"""Generate Explorer's checked-in yt-dlp hostname allowlist.

Requires the pinned yt-dlp version below to be installed in Python's environment.
The generated list is derived from HTTP(S) URLs in yt-dlp's extractor tests; it
does not make network requests.
"""

from __future__ import annotations

import ipaddress
import random
from pathlib import Path
from urllib.parse import urlsplit

import yt_dlp
from yt_dlp.extractor import gen_extractor_classes


EXPECTED_YTDLP_VERSION = "2026.08.19"
OUTPUT = Path(__file__).resolve().parents[1] / "src/explorer/ytdlp_supported_hosts.rs"
RESERVED_DOMAINS = ("example.com", "example.net", "example.org")
RESERVED_SUFFIXES = (".invalid", ".localhost", ".test")


def normalized_host(url: str) -> str | None:
    parsed = urlsplit(url)
    if parsed.scheme not in {"http", "https"} or not parsed.hostname:
        return None

    try:
        host = parsed.hostname.rstrip(".").encode("idna").decode("ascii").lower()
        ipaddress.ip_address(host)
        return None
    except ValueError:
        pass

    if host == "localhost" or host.endswith(RESERVED_SUFFIXES):
        return None
    if any(host == domain or host.endswith(f".{domain}") for domain in RESERVED_DOMAINS):
        return None
    return host


def extractor_test_hosts() -> list[str]:
    # A small number of upstream test fixtures choose a mirror at import time.
    # A fixed seed keeps the checked-in snapshot reproducible.
    random.seed(0)
    hosts: set[str] = set()
    for extractor in gen_extractor_classes():
        if extractor.__name__ in {"GenericIE", "TestURLIE"}:
            continue
        for test in getattr(extractor, "_TESTS", ()) or ():
            if not isinstance(test, dict) or not isinstance(test.get("url"), str):
                continue
            if host := normalized_host(test["url"]):
                hosts.add(host)
    return sorted(hosts)


def main() -> None:
    if yt_dlp.version.__version__ != EXPECTED_YTDLP_VERSION:
        raise SystemExit(
            f"Expected yt-dlp {EXPECTED_YTDLP_VERSION}, found {yt_dlp.version.__version__}. "
            "Update EXPECTED_YTDLP_VERSION intentionally before refreshing the snapshot."
        )

    hosts = extractor_test_hosts()
    lines = [
        "// This file is generated by scripts/generate_ytdlp_supported_hosts.py.",
        f"// Source: yt-dlp {EXPECTED_YTDLP_VERSION} extractor test URLs ({len(hosts)} hosts).",
        "",
        "pub(super) const YTDLP_SUPPORTED_HOSTS: &[&str] = &[",
        *(f'    "{host}",' for host in hosts),
        "];",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
